[project]
name = "adventofagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "agent-starter-pack>=0.29.3",
    "google-adk>=1.21.0",
    "google-genai>=1.56.0",
]
